### PR TITLE
Refactor to migrate package to `{httr2}` (#13) and expand implementation of metadata API (#12)

### PR DESCRIPTION
**Pull request by elipousson**
This is the promised pull request to migrate the package to `{httr2}` for #13 but also includes some expanded implementation of the metadata API for #12. In retrospect, I should have broken this up into multiple smaller pull requests and I totally can understand if it take a while to work through the review.

Here are the highlights of the major changes:

I've removed all calls to `{httr}` and a series of internal helpers (prefixed with "req" with some helpers) use `httr2` to build and perform the API calls. Some of these helpers support a single user-facing function (e.g. `req_delete_record()`), some supporting multiple functions (e.g. `req_perform_offset()`), and some that are used in every request (e.g. `req_auth_airtable()`). There are three of these functions worth noting in particular:

- `airtable_request()` creates an initial request object with `httr2::request()` (using the default values for api_url and api_version).
- `req_airtable_auth()` sets up throttling, error handling, and sets a user agent for the package.
- `req_airtable_query()` handles building the query (with `httr2::req_template()` or `httr2::req_url_query()`) and optionally setting the method with `httr2::req_method()` or adding a body with `httr2::req_body_json()`. This function calls `airtable_request()` if a request isn't provided and calls `req_airtable_auth()` at the end so it is used by many other functions.

I tried to be consistent in the naming and structure for these functions but please call out anything that seems confusing.

Any existing code built on top of rairtable functions should still work. However, for most user-facing functions, the airtable class object is now an optional input parameter. Instead, users can provide an airtable class object, a base id and table id or name, or an Airtable URL. If a user provides a URL, it is passed to the new `parse_airtable_url()` that breaks it apart into a base ID, table ID and view ID.

There is no longer an option to turn off the batch requests and the user-facing functions switch between the single and multiple record API options without informing the user. The progress bars are created by `cli::cli_progress_along()` so they are always on but can be turned off (or turned on more quickly) by modifying the cli package options. There is good documentation for this function here: https://cli.r-lib.org/articles/progress.html#progress-bars-for-mapping-functions-cli_progress_along

There is new vignette with documentation for all of the configuration options which is how I handled the default values that I didn't seem essential to expose to users.

The one potential breaking change is that the airtable class object is now a list created using `vctrs::new_vctr()`. I'm not set on this if you had a strong preference for your existing implementation but keeping everything in a list made it easier to figure out what and how to access the different elements. This also will ease the implementation of a format method for the airtable class which should allow some further simplification of the print and str methods.

The parallel parameter isn't implemented but I thought it might be helpful to do a speed comparison between the old version and this new version to see what difference it makes.

Lastly, I started on an implementation of a `create_table()` function that might make sense to include in this same pull request but isn't essential. Let me know if you have any immediate questions but I'll come back and keep working on the outstanding items later today (or later this week).

### CODE REVIEW

**Comment by matthewjrogers** [comment]
Hi @elipousson -- first off, thank you for all of this work. I really appreciate the thoroughness of your documentation and the scope of what you have contributed.

Having said that, you're correct that it's going to take me some time to look through all of this! My intention is that I would like to take your code and build at least one new function -- I'm targeting `create_base` at the moment -- because I think that will be the best way for me to wrap my head around the workflow. I'll also take some time to sit with the changes you've made -- I'm not opposed to any of them per se (best idea wins, in my book) but want to take some time to think them through. I'm likely to have questions along the way -- I will reach out!

On parallelization,  I originally wrote this packaged because my team at the time was working with bases at the outer limits of what Airtable allows and I wantedevery bit of efficiency I could get for large update and create operations. I think it's likely that parallelization only pays dividends at the extreme end of the user spectrum. Ideally, I would rather not make breaking changes without a prior deprecation warning.

**Comment by elipousson** [comment]
@matthewjrogers – that all makes sense to me. The scope of the changes snowballed a bit but I was able to reuse some existing code from my own `get_airtable_data()` function (which is now implemented as the `read_airtable_records()` variant on `read_airtable()`).

I'd agree that a create_base function sounds like a good way to get your hands around the code and see how it works (and whether my approach fits with your vision and goals for the package). I just added my (not currently working) code for a `create_table()` function as a possible reference.

I also made some further changes this evening to `airtable_base()` to bring the other S3 classes in line with the vctrs classes I used for airtable. While I've done a lot of work with httr2, I actually haven't done much with S3 classes so I've been working from the documentation for vctrs here: https://vctrs.r-lib.org/articles/s3-vector.html and the S3 chapter of Advanced R: https://adv-r.hadley.nz/s3.html

My only uncertainty with re-implementing the parallel parameter is where to put it. I'll hold off on that (and any further significant changes) until you've had time to dig in and share your own thoughts about the new code.

**Comment by elipousson** [comment]
I think I got the parallel parameter set up and working, @matthewjrogers. It may take a little testing to make sure it still works the same way and you're seeing some performance gains.

I forgot to explain the current state of the testing helpers. The tests aren't set up to run on `check()` yet but if you set a test URL with `set_rairtable_test_url()` you can at least run the tests for `airtable()` and `delete_records()` (which effectively includes a test for `insert_records()` also). If you just create a new blank Airtable with the default 3 blank rows, the tests should work as expected.

I have some ideas and questions about the implementation of the airtable class which may belong in a standalone issue discussion more than in this pull request. If that sounds good to you, I can set up a new issue later this week and outline both my questions about the airtable class object implementation, explain the changes I already included in this PR, and suggest some further potential changes.

**Comment by matthewjrogers** [comment]
Thanks @elipousson. On the parallel issue -- on digging into your code, it seems like `httr2` may obviate the need for that functionality. I was using it exclusively for the translation from R data structures to JSON which (as I understand it) `httr2` now handles for us -- I didn't fully grasp this at first. Please correct me if I'm wrong about that. I'm content with the trade off of maintaining less code for slightly worse performance at the extreme ends of Airtable usage. 

On the `airtable` class, I'm always open to discussion -- feel free to open another issue. I've been reading through your PR and expect I'll have time to do some development with the code in the next two weeks or so. I have some preliminary questions I will follow up with shortly. 

So you know, I am definitely going to merge this PR. These are positive changes and my few objections, where I have them, are philosophical rather than substantive. I really appreciate this work. I was particularly excited to see that warning message regarding 'user' field types. I've been meaning to do something about that for a long time!

Anyway, in touch again soon.

**Comment by elipousson** [comment]
Great. We can touch base about the parallel parameter later on. You are correct that httr2 is handling the conversion to JSON and the re-implementation that I added last night only impacts the conversion between data.frames and lists and the transformation of lists into list arrays. Those are pretty fast even for large data.frames so the performance gains may not be worth the extra complexity.

Really appreciate the positive feedback about the pull request and I'll keep an eye out for those questions sometime next month.

**Comment by matthewjrogers** [comment]
Hey there @elipousson 

I haven't yet gotten a chance to work on my `create_base` function using your code, but I have looked through it thoroughly and wanted to get you some initial questions and reactions. I haven't had the time to go quite as deep as I'd like, so if I've misunderstood how something works, please let me know. 

In preface to all of the following, I'm open to discussion on the below. I have organized my responses by category and by strength of opinion (that is, I feel more strongly about the items in section 1 than 2, and within each section I feel stronger about item 1 than item 2, etc.).

## __REQUESTED CHANGES__

----------------------------------

### Limit function exports to user interface functions

Currently, it looks like all of the functions in the package are being exported, including internals. I have a strong preference for only exporting final user-facing functions. This is for two interrelated reasons:

1. Internal function exports will not be useful to the average `rairtable` user. In a normal workflow, the average user is not going to need or want any of the `req_` functions, for instance.
2. Additional exports have a complexity cost. To use the package in this state, a new user might need to navigate a significant number of functions that will not help them solve their problem to find the function they need, whereas exporting only half a dozen or so clearly named functions that perform CRUD operations makes the package much easier to grok and to navigate.

I seem to recall you mentioning that part of your motivation for this PR was to advance other packages/code you were working on, is that correct? If so, I'd be happy to discuss alternative ways we might expose these internals other than a blanket export.

----------------------------------

### Remove `create_records`

`create_records` is probably a better name than `insert_records`, but given that it's just a wrapper over an existing function I would rather remove it. I chose `insert_records` as a name because it helped me remember that I needed to create the fields in Airtable first before I could use `insert_records`. That may not be clear to other people, but I don't think it's confusing enough to merit a breaking change in the code. 

This comes back to my philosophy on complexity (apologies, I'm going to beat this drum a lot in this response!). Having two functions with identical purpose feels significantly less clear than having a single API for adding new data to an Airtable base.


Related, why is there a `req_create_record` function as well as `req_create_records`? It looks like the latter is used and the former is not, so it seems unnecessary to me.

----------------------------------

### Remove `Name` and `Description` fields of Airtable object

This is a nice touch for printing, but I would prefer not to add complexity to the object that doesn't also have a material application. If there is a use for these fields I have not thought of or noticed, please let me know. Otherwise, I would prefer they were removed.

----------------------------------


## __PHILOSOPHY__

These are items where I think the decisions are strategic rather than material and I would like to hear your thoughts before we decide on a final path forward.

----------------------------------

### Multiple user APIs

Most of the function now take either an `airtable` object or the component pieces needed to make the request where previously an `airtable` object was the only option.

I really like the ability to parse a URL in the creation of an `airtable` object -- that's really easy, and great not to have to extract that info from the URL manually or go to the API docs for it.

I admit I'm a little on the fence about this for the other functions. I keep coming back to thinking about a brand new `rairtable` user, and especially those a little newer to R itself. Flexibility is awesome for power users and experts, and (in my experience) daunting for beginners. I have been trying to target the complexity of this package to a low-intermediate user, and having a single API for "connecting" to an Airtable table will be simpler.

I think the other piece is that I'm not sure what this flexibility adds. Personally, I would much rather create a single object in one location in code and then pass it to all of my functions rather than pass around a series of strings.

How do you imagine using this additional mode? If there's a use case for it that I have not thought of, I am prepared to be persuaded.

----------------------------------

### Storing IDs in row names by default

I've gone back and forth on this. Originally, storing the values in row names was the default behavior. After a handful of instances where I inadvertently destroyed row names (most notably when using `dplyr::arrange()`) I decided to make the default behavior storing the values in a column. The advantages of row names are clear -- they are simple, require little thought or effort, and avoid 'surprising' the user with an unexpected column. The downside of course is that they are fragile and subject to loss. 

Why did you decide to change this default behavior?

----------------------------------

### Vector as base for `airtable` object vs. environment

I like the simplicity of not mixing attributes and values in your approach. My rationale for the attributes was that I thought it highly unlikely a user would inadvertently modify those values. I think now that concern was not proportional to the actual risk.

I chose an environment as the base with the idea that future iterations of the package might have the ability to set the state of an `airtable` object (e.g. toggle between keys/PATs). Because of environments reference semantics, this change could be done without reassigning the variable. You've added the ability to pass PATs directly to some of the key functions, which may address this.

I think the question here is this: do you see utility in an Airtable object being able to manage its state? Would it be useful for an Airtable object to be able to have methods attached to it that could pull metadata etc.? Those are the advantages of environments, but I'm curious to hear your thoughts.

----------------------------------

## __PROGRAMMING SUGGESTIONS__

----------------------------------

### Refactor `req_create_records` to use recursion

Currently, `req_create_records` calls `batch_create_records` which calls `req_create_records`. I found this a little confusing at first and I think it could be simplified with some recursion. The following should be functionally identical code without the need for `batch_create_records`

```
req_create_records <- function(req = NULL,
                               ...,
                               data,
                               typecast = TRUE,
                               token = NULL,
                               parallel = FALSE,
                               call = caller_env()) {
  req <- req %||%
    req_auth_airtable(
      req = airtable_request(..., call = call),
      token = token
    )
  
  data <- make_field_list(data, parallel = parallel, call = call)
  n_records <- length(data)
  batch_size <- as.integer(getOption("rairtable.batch_size", 10))
  
  if (n_records > batch_size) {
    
    batched_data <- split_list(data, parallel = parallel, call = call)
    
    format <-
      "{cli::symbol$arrow_right} {action}: {cli::pb_bar} | {cli::pb_percent}"
    
    resp <- map(
      cli::cli_progress_along(batched_data, format = format),
      ~ req_create_records(
        req = req,
        data = batched_data[[.x]],
        parallel = parallel,
        call = call
      )
    )
    
    return(resp)
  }
  
  data <- set_names(data, rep_len("fields", length(data)))
  
  check_bool(typecast, call = call)
  
  req <- httr2::req_body_json(
    req,
    data = list("records" = split_list(data, 1), "typecast" = typecast)
  )
  
  httr2::req_perform(req)
}
```
----------------------------------

### Quick fix 

You had a FIXME note in `insert_records`. You can wrap the `lapply` in a call to `c` to combine into a single list

```
  if (return_json) {
    if (!inherits(resp, "httr2_response")) {
      # FIXME: The body from the batched requests should be combined if possible
      return(c(lapply(resp, httr2::resp_body_json)))
    }

    return(httr2::resp_body_json(resp))
  }
```


----------------------------------

## __MISC DETAILS__

----------------------------------

### Credit should be `c("aut")`, rather than `c("aut", "ctb")`

To my understanding, `ctb` is typically used for minor contributions, and this is far from minor. 'Author' seems most appropriate to me.

----------------------------------

### Parallel no longer needed

I believe we discussed this elsewhere, but I think we can just deprecate parallel wholesale. I'm sorry I had you go to the trouble of adding it!

**Comment by elipousson** [comment]
@matthewjrogers Thanks for this helpful and organized feedback! I've started writing up my responses (and making some of the requested changes) but might take a week or two to get back to you so wanted to make sure you knew I saw the reply.

**Comment by elipousson** [comment]
OK. I'm making some progress on this and just wanted to confirm all of these changes are complete:

- Fixed my role in DESCRIPTION.
- Removed the parallel parameter.
- Added the fix to return a single list when using return_json = TRUE on a batched request.
- Refactored to drop the batch_* helper functions (adding `map_action_along()` to avoid duplicate code)
- Fixed the default value for id_to_col (this was just a mistake – I thought id_to_col = FALSE was the default)
- Removed req_create_record (that was an attempt to implement [this option from the API](https://airtable.com/developers/web/api/create-records#request-fields) but it wasn't working)

Some quick thoughts on the requested changes:

- I exported all the internal functions for two reasons: it allowed me to keep the parameter definitions together with the low-level functions where it is most relevant and then use `@inheritParams` to pull the definitions up into the public-facing functions and I think they could be useful to someone who needs lower-level access to the API to build a custom function or workflow. There may be work arounds for both of these use cases but I'd need to think through how to make that work. I'm not opposed to the change but don't want to lose the flexibility I may need to build wrapper functions around the rairtable functions.
- I would really like to keep the `create_records()` function in place since that is the name of the related method in the Airtable API documentation (I tried to use parallel language to the API for anything I was adding). If the documentation is unclear, I can rewrite to make sure it is evident that `create_records()` is just an alias for `insert_records()`. Ideally, we may be able to add some field validation in the future to avoid any confusion with the two-step process for creating "fields" before you create "records".

I'll come back and share some additional thoughts on the multiple user APIs and vector as base for airtable object soon. I'm hoping making the URL checks more robust and predictable can help make the former approach workable but happy to make the case for the value of this approach.

**Comment by matthewjrogers** [comment]
I did a little testing and it seems that `@inheritParams` works with unexported functions, so I don't think the documentation as written would need to change much.

On the flexibility piece, I had two thoughts

1. For simple applications that are not intended to go to CRAN, you can access unexported functions from a package using `:::`, which would make those options available anywhere you need them (again, CRAN does not allow this, so if the intention is to make another CRAN package that won't work)
2. Is there a _subset_ of low-level api functions that can be exposed to provide the flexibility you want while also maintaining a (relatively) minimal UI? Say 5 functions, give or take a few? I realized my major concern is the volume of exported functions, not the idea of also providing lower level functionality through `rairtable` per se. Coupled with good documentation, I could pretty happily get on board with this.

**Comment by elipousson** [comment]
Sounds great. I think I can cut back the exported functions to a handful of essential utility functions and make sure the documentation is clear that they're really intended for developers only. I don't think I anticipate a need to export anything else right now.

FWIW – I think the issue that I've encountered in the past is due to tagging non-exported functions with `@noRd` but, evidently, as long as I don't include an `@export` tag it works just fine. Glad to learn this!

Regarding the feedback on **Multiple user APIs**, my use case is the expectation that I usually won't need an airtable object as an intermediary. Instead, I'll just grab a URL from my browser and pass it directly to `read_records()` or `create_records()` as needed. This may be a personal preference but I'm hoping that keeping those parameters tucked away in `...` will keep it from getting confusing for users.

Regarding my case for keeping **`create_records()`**, I realized that I'd been inconsistent with my own intent to keep naming practices consistent with the official API documentation which is why I renamed `read_airtable_records()` and `read_airtable_record()` to `list_records()` and `get_record()`.

Regarding using a **vector as base for airtable object vs. environment**, I actually don't have much experience working with object states (or S3 in general). Based on my limited understanding, it seems like overkill for Airtable API access but I may just be missing the possibilities.

My oustanding question about airtable objects (which may benefit from a separate issue for a separate discussion) is how to handle multiple tables and multiple views within a single object. In the existing version of `rairtable` it seems like a airtable object represents a single table using the default view or a supplied view. But the metadata API makes it easy to pull down a list of all of the views available for a table so the object could hang on to that information for users to access as needed. That is also one reason why I added the name and description information to the object data model – I think keeping metadata along with the ID values and request URL has potential to be useful.

**Comment by elipousson** [comment]
Making progress! I think there may just be two internal request functions that I'd like to see exported: `request_airtable()` and `req_airtable()` (formerly named `airtable_request()` and `req_query_airtable()`). I also added a feature to trigger helpful errors if a user passes a shared link to an Airtable base instead of the actual parse-able view URL.

**Comment by elipousson** [comment]
I think I got it down to just two developer-oriented functions in the exports: `request_airtable()` and `req_airtable()`. I also did a ton of clean-up to input checking with a particular focus on URLs in an effort to make sure the multiple APIs don't create any significant confusion.

I also added a couple new functions along the way:

- `create_field()` and `update_field()` which do what they say
- `get_base_schema()` and `list_base_tables()` to provide a no custom-class alternative to `airtable_base()`

For `airtable_base()`, I realized that the function had only been added to the development version so I went ahead and removed the metadata_api_url_pattern parameter (rather than flagging it as deprecated).

This flurry of development is brought to you by my procrastination on other projects – but I'm honestly I think this is coming together pretty well. I went ahead and started the process of updating the README although, clearly, the tests need to be worked out before this branch could be merged into main.

**Comment by matthewjrogers** [comment]
Apologies for the radio silence! 

This is looking great -- a pair of exported functions is perfect.

I haven't really thought about `airtable` objects as programmatically generated things much prior to this, but it's a valid point that the metadata API wrappers make it increasingly likely that someone will receive an `airtable` object they didn't make by hand. Given that as context, I'm ok with leaving those metadata fields as options. 

On the question of handling multiple tables with `airtable` objects -- I think the `airtable` object can remain a representation of a single table and the metadata function `airtable_base` can return a list of tables that can be passed to the CRUD functions. I believe this is how this works now.

On multiple views, this might be an argument for environments as base for `airtable` objects. There could be a method or function to set the active view from among a list stored in the object. This could work in a vector implementation, but I'm pretty sure you'd have to reassign the object which doesn't feel intuitive to me. E.g.

```
atb <- airtable(...)

# if `airtable` obj is vector

atb <- set_active_view(atb, view = 'foo')

# if `airtable` obj is environment

set_active_view(atb, view = 'foo')

```
I agree that it might be worth pulling this discussion into it's own thread.

Happy to collaborate on tests. My hope and intention is that after we get this merged to dev sometime in the near future, we can push to CRAN over the summer.

I wish I procrastinated by contributing to open source :)

**Comment by elipousson** [comment]
No apologies needed at all.

I've been using this development branch for a few projects (I use Airtable routinely at work for storing small bits and pieces of structured data) and keep finding minor issues that I've been knocking out as the opportunity comes up. Getting the package working with table names as well as table IDs required a little extra complexity for input checks so if you see any opportunities for streamlining the code, please feel free to flag them.

I started implementing `httptest2::with_mock_dir()` using a new Airtable account just dedicated for testing. If you can provide me with an email linked to an Airtable account, I can share the test base with your email so you can run the live tests directly.

I just set up an issue with some thoughts around airtable class objects so look forward to continuing the conversation there. One function that I'd also really like to get working before you merge this pull request is `create_table()`. I've tried a couple times to get it working and I somehow can't figure out the right way to structure the request body correctly.

**Comment by elipousson** [comment]
Everything could use some testing but I think I got `create_table()` and `update_table()` figured out this evening! I also added a set of functions for listing, creating, and deleting comments. Not counting the webhook API, that may be close to full coverage of the API endpoints available for non-enterprise accounts.

**Comment by matthewjrogers** [comment]
That's awesome. I'll be able to dig in a little bit around the 4th, and then I think we're getting close to merging this thing. Appreciate all your work!

**Comment by elipousson** [comment]
I had one last idea on my personal wishlist: the ability to copy field configuration from an existing table metadata. I made good progress on implementing this over the weekend and should be able to finish working out a few bugs and adding a few more tests before the weekend. I'll email you the token I'm using for testing (or the secret for decoding the token if I'm able to get that working with httr2).

**Comment by elipousson** [comment]
Just a quick heads up that I've implemented a few more features based on the potential of using a table model for validation including:

- adding the new `copy_table_config()` and `get_field_config()` functions
- field and sort parameter validation for `read_records()` and `list_records()`
- reordering columns to match the table model for `read_records()`, `list_records()`, and `get_record()`

I also added a .name_repair parameter to handle the possibility of a name conflict between the airtable ID column name and the existing columns within an Airtable base.

I also replaced the return_json parameter with the more intuitive (IMHO) return_data or return_records parameters and exposed the simplifyVector parameter (and re-working a few things so they'll handle either data frame or list inputs).

I've expanded test coverage and improved input checks to make sure this additional capacity doesn't create any difficult to trouble-shoot errors for users but also understand that most folks may not need this level of complexity. I figure it would be helpful to add a vignette showing how to use the schema and model parameters (and why someone may want to).

I hope it isn't a pain that this pull request has been a moving target! I figured if you wouldn't have time to review until later this week that I'd push to finish up a few more things that I think should be useful for my workflow (and others). I've been learning a lot as I'm building this out and really looking forward to seeing it up on CRAN!

**Comment by elipousson** [comment]
And I just added a `create_base()` function that can use the list of tables from a base schema to create a new table array (effectively copying an existing base with the exception of the record link columns and a few others types that are difficult to copy over). A new metadata API vignette should be finished by the end of the week!

**Comment by matthewjrogers** [comment]
Thanks for all of this, this is a tremendous amount of work. I will dig in over the next couple of days.

My suggestion, for what it's worth, is that we may want to pin the current state as the next release (pending any bugs/documentation changes) and switch focus to preparing a CRAN release. We can always think about another minor version change in the next 6 months or so.

**Comment by elipousson** [comment]
@matthewjrogers That makes a lot of sense. I'll put a pause on any new features and look out for feedback! Your prior comments were helpful and well-organized so feel free to take that same approach or edit the pull request directly.

There are a couple things I'd suggest looking out for (based on the issues I've caught so far):

- Unexpected or undocumented behavior using the `airtable_request()` and get ID functions (e.g. is it clear that passing a field URL to `get_record()` can set the record ID but won't override a record ID if it is supplied?)
- Consistent handling of table names (there are some places a table name works and some places the functions only handle a table ID and I'm not certain which are which)
- Predictable/consistent type outputs (once I started adding in the option to pass the schema and model as a parameter, I realized it would be handy to be able to get API responses as lists rather than always coercing to a data frame - but now the documentation is potentially out of date and I want to make sure it is clear what functions return what types of data). For example, I think `get_table_model()` may need a stricter limit on the structure of the permitted output

There are also a few places where I think `{vctrs}` may be a useful substitute for the existing helper functions – especially since it has functions that can handle data frames and lists agnostically. But, that can probably wait for a minor version update so I wouldn't suggest it as a priority.

**Comment by matthewjrogers** [comment]
@elipousson -- wanted to give you a heads up that, unfortunately, it might be a bit before I get back to this. My hometown in Vermont got hit pretty hard in the recent flooding -- going to try and carve out the time for this, but my timeline for review has dilated. Wanted to make sure you know this is not forgotten

**Comment by elipousson** [comment]
Really sorry to hear that you and your neighbors are so hard hit. I appreciate the heads up and hope you and your town get the support you need to rebuild and recover. Open source will wait!

**Comment by matthewjrogers** [comment]
@elipousson finally found some time for this, and (anticlimactic, perhaps) I think this looks excellent. I am going to merge this pull request and start the checks needed to get this to CRAN. You may see more from me over the course of the next week or so if anything needs to be done to satisfy CRAN requirements related to your code. I am optimistic that this will go smoothly. I'll leave the PR open until we get that buttoned up.

Thank you, once again, for your extensive and thoughtful work on this.

**Pull request merged**
